# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyReactNativeApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyReactNativeApp
  pod 'AppCenter/Crashes', '~> 1.1.0'
  pod 'AppCenter/Analytics', '~> 1.1.0'
  pod 'AppCenterReactNativeShared', '~> 1.1.0'

  


  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  target 'MyReactNativeAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MyReactNativeApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyReactNativeApp-tvOS

  target 'MyReactNativeApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
